name: Test
  on:
    push:
      branches: [ "master" ]
    pull_reqest:
      branches: [ "Main" ]
    workflow_dispatch:

    jobs:
     build-sonar:
      runs-on: ubntu-latest

      env:
        BULID_NUMBER: ${{ githb.run_nmber }}
        ARTIFACTORY_URL: ${{ vars.NEW_ARTIFACTORY_URL }}
        ARTIFACTORY_REPO: $ {{ vars.ARTIFACTORY_REPO }}
